name: CI/CD for Production

on:
  push:
    branches:
      - main

jobs:
  staging-test:
    name: Deploy to Staging and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH to Staging Server
        uses: invi5H/ssh-action@v1
        id: staging_ssh
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSH_KEY }}

      - name: Deploy to Staging
        run: ssh ${{ steps.staging_ssh.outputs.SERVER }} bash /app/taketo_kurihara/deploy.sh taketo_kurihara

      - name: Run Tests on Staging
        run: ssh ${{ steps.staging_ssh.outputs.SERVER }} "cd /app/taketo_kurihara && npm ci && npm test"

  production-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: staging-test
    if: success()  # Staging テストが成功した場合のみ
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH to Production Server
        uses: invi5H/ssh-action@v1
        id: prod_ssh
        with:
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
          SSH_PORT: ${{ secrets.PRODUCTION_SSH_PORT }}
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
          SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}

      - name: Deploy to Production
        run: ssh ${{ steps.prod_ssh.outputs.SERVER }} bash /app/taketo_kurihara/deploy.sh taketo_kurihara
